### PR TITLE
LRQA-72753 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-72753

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test

**Comment by patriciajeanperez** [comment]
Can you also try and see if PageEditor.changeLocale will work instead of creating new paths and macros?

**Comment by melodywu** [comment]
> Can you also try and see if PageEditor.changeLocale will work instead of creating new paths and macros?

Thanks. I will try

**Comment by melodywu** [comment]
ci:test:bundle

**Comment by melodywu** [comment]
ci:test

**Comment by melodywu** [comment]
ci:test

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:bundle

**Pull request closed without merging**
