### PR TITLE
LRQA-74500 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-74500

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test

**Comment by melodywu** [comment]
ci:test:sf

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
ci:stop

**Comment by gaborlovasdotcom** [comment]
ci:top

**Comment by gaborlovasdotcom** [comment]
ci:stop

**Pull request closed without merging**
