### PR TITLE
LRQA-73136 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-73136

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test

**Comment by pyoo47** [comment]
@melodywu I was forced to kill your `ci:test` build because it was stuck in a very long queue. Are you sure you need to run `ci:test` instead of `ci:test:relevant`? `ci:test` is very costly in terms of ci infrastructure resources and should be run very sparingly.

**Comment by melodywu** [comment]
ci:test:relevant

**Pull request closed without merging**
