### PR TITLE
LRQA-74974 | master

### PR DESCRIPTION
**Pull request by JingyuanZhao**
https://issues.liferay.com/browse/LRQA-74974

### CODE REVIEW

**Comment by JingyuanZhao** [comment]
ci:test:sf

**Comment by JingyuanZhao** [comment]
ci:test:sf

**Comment by JingyuanZhao** [comment]
ci:test:sf

**Comment by melodywu** [comment]
Ok you can edit something

**Comment by JingyuanZhao** [comment]
ci:test:sf

**Pull request closed without merging**
